// Generated by https://quicktype.io

export interface ProductsResponse {
    response: Product[];
    success:  boolean;
    error:    null;
}

export interface Product {
    _id:           string;
    name:          string;
    brand:         string;
    price:         number;
    category:      Category;
    type:          string;
    heading:       Heading;
    image:         string;
    size?:         string;
    color:         string;
    state:         string;
    __v:           number;
    userFavorites: string[];
}

export enum Category {
    Hombre = "hombre",
    Mujer = "mujer",
    Niños = "niños",
}

export enum Heading {
    Accesorio = "Accesorio",
    Calzado = "Calzado",
    Indumentaria = "Indumentaria",
}
