// Generated by https://quicktype.io

export interface SigninResponse {
    response: Response;
    message:  string;
    success:  boolean;
}

export interface Response {
    userData: UserData;
    token:    string;
}

export interface UserData {
    id:          string;
    name:        string;
    email:       string;
    information: Information;
}

export interface Information {
    image:         Image;
    paymentMethod: PaymentMethod[];
    _id:           string;
    user:          string;
    phone:         string;
    address:       string;
}

export interface Image {
    url:       string;
    public_id: string;
}

export interface PaymentMethod {
    bv?:  string;
    trf?: string;
}
